
ALTER TABLE `dd_business_extra`
ADD COLUMN `Skype` varchar(50) DEFAULT NULL,
ADD COLUMN `SocialMedia` varchar(250) DEFAULT NULL;


REPLACE INTO `dd_user` (Id,Username,Password,FirstName,LastName,Email,UserType,CompanyName,Address1,Address2,City,State,PostCode,Country,Phone,PaymentType,PaymentAccount,GoogleAnalytics,Lang,UserVerification,Created,Modified,Active,Validated)
VALUES
(1020,'Tejinder','Zoop IT Solutions Ltd','Tejinder', 'Chawla','tejinder@zoop.co.nz','supplier','Zoop IT Solutions Ltd','Level 31 Vero Centre, 48 Shortland Street, Auckland-101 0  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1021,'Matthew','Brady Solutions Limited','Matthew', 'Brady','brady.solutions@gmail.com','supplier','Brady Solutions Limited','PO Box 12 622, Wellington 6144  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1022,'KimSmi','Smiths Shcctmetctls Ltd.','Kim', 'Sieber','kim.sheetmetols@xtra.co.nz','supplier','Smiths Shcctmetctls Ltd.','Takapuna Auckland 122 Sunnybrae Rd,  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1023,'KimDew','Dewatering Specialist Ltd','Kim', 'Sieber','kim@dewatering.co.nz','supplier','Dewatering Specialist Ltd','124 Sunnybrae Rd/Hillcrest/Auckland 0627  ','PUMP HIRE/SALES/REPAIRS/PARIS/GENERATORS/TRENCH SHIELDS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1024,'Tessa','Eduplay Child care','Tessa', 'Apa','tessa@edupac.co.nz','supplier','Eduplay Child care','Auckland  1 Ranier St, Ellerslie,  1060','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1025,'Tamia','thebusinessconnection','Tamia', 'Sparks','tania@busconnect.co.nz','supplier','thebusinessconnection','Greenlane 2 Kalmia Street, Ellerslie/Greenlane Auckland PO BOX 62550, Kalmia Street','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1026,'Chris','Time Out Beauty','Chris', 'Graham','timeout.beauty@yahoo.co.nz','supplier','Time Out Beauty','1/105 Landscape Rd Mt Eden Auckland  ','TIME OUT BEAUTY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1027,'Alison','Steiner Ceramics','Alison', 'Steiner','alison@steinerceramics.co.nz','supplier','Steiner Ceramics','PO Box 52 111, King Stand Auckland 1352, New Zealand  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1028,'Rachael','HWI Limited Chartered Accountants','Rachael', 'Trotter','rtrotter@hwi.co.nz','supplier','HWI Limited Chartered Accountants','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1029,'Black','Black Gunz','Black', 'Gunz','blackgunzpaintball@gmail.com','supplier','Black Gunz',' Manukau Auckland 20B Norman Spencer Drive  2104','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1030,'Philip','All Round Security Ltd','Philip', 'Walsh','allround@xtra.co.nz','supplier','All Round Security Ltd','   P0 Box 82288 Highland Park Manukau 2143  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1031,'Steph','','Steph', 'Cawte','steph@eyewearbysteph.co.nz','supplier','','   1A Wotton Road, Remuera, Auckland 1050  ','Dispensitrg Optician',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1032,'Jeremy','Mosh','Jeremy', 'Marks','jeremy@mosh.co.nz','supplier','Mosh','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1033,'AndrewPure','PURESEO','Andrew', 'Macdonald','andrew@pureseo.co.nz','supplier','PURESEO','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1034,'AndrewWord','Word Works ','Andrew', 'Healey','andrew@word-works.co.nz','supplier','Word Works ','   28 Lunn Avenue, Mt Wellingtc  1072','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1035,'NickDot','DOT KIWI LTD','Nick', 'Simmons','nick@dot-kiwi.com','supplier','DOT KIWI LTD','   P0 Box 8207, Symonds Street, Auckland 1150  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1036,'Jodie','','Jodie', 'Kirkwood','jodie.kirkwood@regus.com','supplier','','Level10, 21 Queen Street Auckland, New Zealand 1010 1500 / 1 600 Cities 1100 Countries  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1037,'Greg','NEW ZEALAND FINANCIAL PLANNING LTD','Greg', 'Moyle','greg@akld.nzfp.co.nz','supplier','NEW ZEALAND FINANCIAL PLANNING LTD','   LEVEL 1, 198 FEDERAL STREET AUCKLAND I  PO BOX 105-190  AUCKLAND CITY 1143 ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1038,'Birgit','Image Lounge','Birgit', 'Utech','birgit@imagelounge.co.nz','supplier','Image Lounge','','Photography',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1039,'DavidKonica','Konica Minolta','DAVID', 'WHARAM','david.wharam@konicaminolta.co.nz','supplier','Konica Minolta',' Grafton Auckland Cnr Khyberpass & Nugent Street  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1040,'Lara','Cogege Hill Productions','Lara', 'Fleming','lara@collegehill.co.nz','supplier','Cogege Hill Productions','   651b Rosebank Road, Avondale  PO Box 47-777, Ponsonby Auckland 1144 ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1041,'DEBRA','admin Corp','DEBRA', 'CLARK','debra.clark@admincorp.co.nz','supplier','admin Corp','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1042,'Josko','Radi Call','Josko', 'Sestan','josko.sestan@radicall.co.nz','supplier','Radi Call','   PO Box 340 197, Birkenhead, Auckland, 0746  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1043,'RICHARD','RICHARD OLIVER FINANCIAL CARE LTD','RICHARD', 'OLIVER','rgol@ihug.co.nz','supplier','RICHARD OLIVER FINANCIAL CARE LTD','   99 Kohimarama Road, Misson Bay, Auckland 1071  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1044,'NISHA','KONICA MINOLTA','NISHA', 'DEAN','supplies@konicaminolta.co.nz','supplier','KONICA MINOLTA','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1045,'Leanne','NZ Business Magazine','Leanne', 'Moss','leanne@nzbusiness.co.nz','supplier','NZ Business Magazine','  North Shore  14c Vega Place  PO box 65 092 mairangi bay  0754 ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1046,'Barry','ACC ONLINE','Barry', 'Vincent','savings@acconline.co.nz','supplier','ACC ONLINE','   P.O. Box 304013 Hauraki Corner, Auckland  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1047,'Gaye','Equilibrium','Gaye', 'Adrett','goue@equilibriuminteriori.co.nz','supplier','Equilibrium',' Remuera Auckland PO Box 128 293  1541','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1048,'Grant','mtf Warwick Cashmore','Grant', 'Cashmore','grant.cashmore@mtf.co.nz','supplier','mtf Warwick Cashmore','516 Great South Road PO Box 74323 Greenlane Auckland1546  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1049,'Sally','Marketing Association','Sally', 'Filmer','sally@marketing.org.nz','supplier','Marketing Association','L1, 61 wellington street, FreemansBay PDBox47681, Ponsonblcaucklandn44  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1050,'Graeme','Marketing Makeover','Graeme', 'McGillivray','graeme@marketing-makeover.co.nz','supplier','Marketing Makeover','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1051,'Jacqueline','Alexandra Park','Jacqueline', 'MacLeod','jacqueline@alexpark.co.nz','supplier','Alexandra Park','PO Box 26021, EPSOM, AUCKLAND 1344  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1052,'Allan','Zeald Ltd','Allan', 'Kent','allan.kent@zeald.com','supplier','Zeald Ltd','Auckland Level2, Building E, 42 Tawa Drive, Rosedale   P0 Box 301 288 Albany','','Auckland','0752',NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1053,'Ross','Kinetics Group Limited','Ross', 'Johnson','ross.johnson@kinetics.co.nz','supplier','Kinetics Group Limited','   p.O. Box 109477, Newmarket 1149 Auckland, New Zealand  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1054,'Trent','Kettle Korn','Trent', 'Brock','trent@kettlekorn.co.nz','supplier','Kettle Korn','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1055,'Nelson','Fuzed','Nelson', 'Williams','nelson@fuzed.co.nz','supplier','Fuzed','Auckland 4 Western Springs Road, Kingsland PO Box 26 302, Epsom 1344, Auckland ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1056,'KarenSign','NZ SIGN SOLUTIONS','Karen', 'Browne','karen@signsolutions.co.nz','supplier','NZ SIGN SOLUTIONS','   Unit 1, 70 Forge Road, Silverdale Auckland, New Zealand  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1057,'GORDONGLEN','','GORDON GLEN', 'WATSON','gordonglenwatson@gmail.com','supplier','','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1058,'RAYMOND','Computer Troubleshooters','RAYMOND', 'WIDJAJA','raymondw@comptroub.com','supplier','Computer Troubleshooters','   9 Dianthus Place, Browns Bay PO Box 305 144, Triton Plaza, Auckland 0757  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1059,'DaveExp','Experience On tap','Dave', 'Wylie','david.wylie@experienceontap.co.nz','supplier','Experience On tap','   P0 Box 39781 Howick 2145  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1060,'Trish','Enprise Solutions Enprise','Trish', 'Glover','trishg@enprise.co.nz','supplier','Enprise Solutions Enprise','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1061,'Colleen','Quality Hotel Lincoln Green','Colleen', 'Acton','colleena@lincolngreen.co.nz','supplier','Quality Hotel Lincoln Green','  Auckland 159 Lincoln Rd, Henderson, Auckland PO Box PO Box 21-366, Auckland ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1062,'Anita','Regus','Anita', 'Harris','anita.harris@regus.com','supplier','Regus','Level10, 21 Queen Street Auckland, New Zealand 1010  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1063,'JULIAN','MOSH, CO.NZ','JULIAN', 'THOMPSON','julian@mosh.co.nz','supplier','MOSH, CO.NZ','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1064,'Marj','Anti aging world','Marj', 'Mulholland','info@anti-agingworld.com','supplier','Anti aging world','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1065,'Paul','HWI Limited Chartered Accountants','Paul', 'Leighton','pleighton@hwi.co.nz','supplier','HWI Limited Chartered Accountants','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1066,'SUSIE','US','SUSIE', 'PIERCE','susie@unisonworkspaces.co.vn','supplier','US','PO Box 137311. PARNELL AUCKLAND 1151 lEVEL 2, 165 THE STRAND, PARNELL, AUCKLAND 1010 ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1067,'Pravin','Content Forest','Pravin', 'Daryani','pravin@contentforest.com','supplier','Content Forest','Pravin. apeforest','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1068,'Terrene','Couriu Post','Terrene', 'Nair','tenene.nair@couriepostco.nz','supplier','Couriu Post','   15 Ride Way Albany A,auckland  P0 Box 101145 Nom Shore Mail Centre Glenfield 0145  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1069,'Tabata','E SERVCO RP','Tabata', 'Sommerville','tsommerville@servcorp.co.nz','supplier','E SERVCO RP','Level 31 Vero Centre 48 Shortland Street Auckland 1010 New Zealand  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1070,'Pedro','ENZSA NZ LTD','Pedro', 'Rozas','enzsa.led@gmail.com','supplier','ENZSA NZ LTD','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1071,'Brendan','Need A Nerd','Brendan', 'Ross','bross@needanerd.co.nz','supplier','Need A Nerd','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1072,'DANIEL','Cornerstone Services','DANIEL', 'Relf','daniel.relf@cornerstoneservices.co.nz','supplier','Cornerstone Services','   P0 Box 9303, Newmarket, Auckland 1149  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1073,'Darin','West tec','Darin', 'Kitching','darin@westtec.co.nz','supplier','West tec','   220b Bush Road, Albany Takapuna, Auckland  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1074,'Bianca','LawDownUnder','Bianca', 'Mueller','info@lawdownunder.com','supplier','LawDownUnder','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1075,'Kate','SERVCORP','Kate', 'Turska','kate.turska@servcorp.co.nz','supplier','SERVCORP','   Level 27 PWC Tower, 188 Quay Street Auckland 1010 New Zealand  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1076,'Rob','Excelerate','Rob', 'Jones','rob.jones@excelerate.co.nz','supplier','Excelerate','   Level 27, PWC Tower 188 Quay St. Auckland, 1010  1010','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1077,'Outsource','Outsource your accounts Ltd','', '','oya@outlook.co.nz','supplier','Outsource your accounts Ltd','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1078,'Brian','Thexton Armstrong Bamforth','Brian', 'Bamforth','brian.bamforth@thextonarmstrong.co.nz','supplier','Thexton Armstrong Bamforth','   63 Compass Point Way Half Moon Bay Auckland 2012  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1079,'Mayra','GKIC','Mayra', 'Matson','moyra@makeadifferencemarketing.co.nz','supplier','GKIC','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1080,'Sriram (Ram)','Inmedia','Sriram (Ram)', 'Gudipoodi','ram@inmediaconcepts.com','supplier','Inmedia','  Auckland  39 Maui Pomare Street, Blockhouse Bay  0600','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1081,'DaveSpirited','Spirited Decisions Brady Solutions Limited','Dave', 'Brady','brady.solutions@gmail.com','supplier','Spirited Decisions Brady Solutions Limited','P 0 Box 12 622 Wellington 6144 New Zealand  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1082,'HelenAntiAging','Anti-Aging W RLD AGING SOLUTIONS','Helen', 'Mitchell','','supplier','Anti-Aging W RLD AGING SOLUTIONS','','Marj Mulholland',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1083,'DaveBrady','Brady Solutions Limited','Dave', 'Brady','brady.solutions@gmail.com','supplier','Brady Solutions Limited','   P 0 Box 12 622 Wellington 6144 New Zealand  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1084,'Helen','Anti Aging world Solutions','Helen', 'Mitchell','info@anti-agingworld.com','supplier','Anti Aging world Solutions','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1085,'Garry','Modern Signs','Garry', 'Campbel','garry@modernsigns.co.nz','supplier','Modern Signs','','Signage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1086,'Marie','NZSTI','Marie', 'Dai','hutech@xtra.co.nz','supplier','NZSTI','','Translator and Interpreters',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1087,'Mag','Roberts Co.,Ltd','Mag', 'Roberts','9999mag@gmail.com','supplier','Roberts Co.,Ltd','','accounting',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1088,'Amy','Richard Oliver Financial card lrd','Amy', 'Oliver','1272256513@qq.com','supplier','Richard Oliver Financial card lrd','','Insurance',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1089,'David','Beauchamp Enterprised Ltd','David', 'Beachen','beauchamp.enterprises@yahoo.com','supplier','Beauchamp Enterprised Ltd','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1090,'David3','Clavio (g) Cozee.CO.nz','David', 'Amato','','supplier','Clavio (g) Cozee.CO.nz','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1091,'Jillian','AJPark','Jillian', 'Lim','jillian.lim@ajpark.com','supplier','AJPark','   Level14, 29 Customs Street West Auckland 1010 PO Box 565, Auckland 1140 New Zealand  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1092,'Lynn','The Treasury','Lynn', 'Lai','lynn.lai@treasury.govt.nz','supplier','The Treasury','New Zealand   1 The Terrace P0 Box 3724 Wellington 6140  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1093,'Kirsten','Engex Ltd','Kirsten', 'Dovey','kirsten@engex.co.nz','supplier','Engex Ltd','   KIRSTEN DOVEY BE (hons) Geneva/Manaaer  ','Carbon Free Manafacturing Facility',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1094,'Sasha','Two\'s Company','Sasha', 'Madarasz','','supplier','Two\'s Company','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1095,'DR','AUT','DR', 'THIEN','george.thien@aut.ac.nz','supplier','AUT','Level1, 46 Wakefield Street, Auckland 1010, NZ Private Bag 92006, Auckland 111 2, NZ  ','Faculty of Business and Law',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1096,'Igor','Vadacom','Igor', 'Portugal','igorp@vadacom.co.nz','supplier','Vadacom','P.O. Box 108-146 Symonds St Auckland, New Zealand  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1097,'DianneBrowns','Browns Bay Realty Ltd','Dianne', 'Moore','dianne.moore@raywhite.com','supplier','Browns Bay Realty Ltd','   11 Clyde Road, Browns Bay, Auckland 0630, New Zealand  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1098,'Andrew','Everyday people','Andrew', 'Brownlee','andrew@everydayjobs.co.nz','supplier','Everyday people','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1099,'SAM','TOAST','SAM', 'KERR','sam@toast.co.nz','supplier','TOAST',' Takapuna Auckland 27 Taharoto Road  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1100,'Charlene','Carpet Clearning and Stain Removal Specialists','Charlene', 'Mayes','northshoreandrodney@saywow.net.nz','supplier','Carpet Clearning and Stain Removal Specialists','   P0 Box 427 Whangaparaoa 0943  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1101,'Karen','The Home Loan Store','Karen', 'Lewis','karen@thehomeloanstore.co.nz','supplier','The Home Loan Store','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1102,'LAURIE BROWN','driveline','LAURIE BROWN', 'HAYSOM','laurie@driveline.co.nz','supplier','driveline','7A-65 Paul Matthews Road, Albany, North Shore PO Box 302682, North Harbour, North Shore 0751  ','Finance, leasing and fleet management',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1103,'Tristan','Connell Building Contractor Ltd','Tristan', 'Connelly','cbcontractors@xtra.co.nz','supplier','Connell Building Contractor Ltd','   P0 Box 303 199 North Harbour North Shore 0751 ENOVATIONS AND EXTENSI ONS KITCHENS AND BATHROOM  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1104,'Dianne','ByDizine','Dianne', 'Carian','dianne@bydizine.co.nz','supplier','ByDizine','P.O. Box 31796, Milford, Auckland 0741','Interior Doslgnor & Colour Spuclnllst',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1105,'Lemke','Webpartners','Lemke', 'Wapstra','lemke@webpartners.co.nz','supplier','Webpartners','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1106,'TonySands','SANDS & ASSOCIATES LI MITED','Tony', 'Sands','tony@sanda.co.nz','supplier','SANDS & ASSOCIATES LI MITED','7 Milford Road PO Box 31008, Milford, Auckland 0741  ','Accounting',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1107,'Jess','Sendsational Gift','Jess', 'Daniell','enquire@sendsationalgifts.co.nz','supplier','Sendsational Gift','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1108,'Heath','TRADE Floor Sanding','Heath', 'Nixon','henixon@xnet.co.nz','supplier','TRADE Floor Sanding','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1109,'Kim','HEAT Pump Services Ltd','Kim', 'Neville','kim@heatpumpservices.co.nz','supplier','HEAT Pump Services Ltd','PO Box 84349, Westgate, Auckland TOLL FREE 0508 AIRCON  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1110,'Tony','Laser Plumbing Mairangi Bay','Tony', 'Hyland','mairangibay@laserplumbing.co.nz','supplier','Laser Plumbing Mairangi Bay','','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1111,'Lyndell','Gardens Realised','Lyndell', 'Shannon','lyndell@ihug.co.nz','supplier','Gardens Realised','20 Barlow Place, Birkenhead, North Shore  ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1),
(1112,'Margaret','Klassic Kitchens','Margaret', 'Roberts','klassic@xtra.co.nz','supplier','Klassic Kitchens','248 Archers Road PO BOX 40 149, Glenfield ','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'en-uk',NULL, NOW(), NOW(),'Yes',1);


REPLACE INTO `dd_business_extra` (User, Url)
VALUES
(1020,'http://www.zoop.co.nz'),
(1023,'http://www.dewatering.co.nz'),
(1024,'http://www.ellersliechildcare.co.nz'),
(1025,'http://wwww.officehelp.co.nz'),
(1027,'http://www.steinerceramics.co.nz'),
(1028,'http://www.hwi.co.nz'),
(1029,'http://www.blackgunz.co.nz'),
(1030,'http://www.allroundsecurity.co.nz'),
(1031,'http://www.eyewearbysteph.co.nz'),
(1032,'http://mosh.co.nz'),
(1033,'http://www.pureseo.co.nz'),
(1034,'http://www.word-works.co.nz'),
(1035,'http://www.dot-kiwi.com'),
(1037,'http://www.nzfp.co.nz'),
(1038,'http://www.imagelounge.co.nz'),
(1040,'http://www.collegehill.co.nz'),
(1041,'http://www.admincorp.co.nz'),
(1042,'http://www.radicall.co.nz'),
(1043,'http://www.oliverinsurance.co.nz'),
(1044,'http://Konicaminolta.co.nz'),
(1045,'http://www.nzbusiness.co.nz'),
(1046,'http://www.acconline.co.sg'),
(1047,'http://www.equilibriuminteriort.co.nz'),
(1048,'http://www.mtf.co.nz/greenlane'),
(1049,'http://www.marketing.org.nz'),
(1050,'http://www.marketing-makeover.co.sg'),
(1051,'http://www.alexandrapark.co.nz'),
(1052,'http://www.zeald.com'),
(1053,'http://www.kinetics.co.nz'),
(1054,'http://www.kettlekorn.co.nz'),
(1055,'http://www.fuzed.co.nz'),
(1056,'http://www.signsolutions.co.nz'),
(1058,'http://www.computertroubles.co.nz'),
(1059,'http://www.expenenceontap.co.nz'),
(1060,'http://www.enprise.co.nz'),
(1061,'http://www.qualityhotellincolngreen.co.nz'),
(1062,'http://regus.co.nz'),
(1064,'http://www.anti-agingworld.com'),
(1066,'http://www.unisonwoflkspaces.co.hk'),
(1067,'http://www.contentforest.com'),
(1069,'http://www.servcorp.co.nz'),
(1071,'http://www.needaanerd.co.nz'),
(1073,'http://westtec.co.nz/'),
(1074,'http://lawdownunder.com'),
(1075,'http://www.servcorp.co.nz'),
(1076,'http://www.excelerate.co.nz'),
(1077,'http://www.outsourceyouraccounts.co.cn'),
(1078,'http://www.thextonarmstrong.co.nz/bamforth'),
(1079,'http://www.gkic.co.nz'),
(1080,'http://www.inmediaconcepts.com'),
(1082,'http://www.anti-agingworld.com'),
(1084,'http://www.anti-agingworld.com'),
(1090,'http://www.cozee.co.nz'),
(1091,'http://www.ajpark.com'),
(1095,'http://www.aut.ac.nz'),
(1096,'http://www.vadacom.co.nz'),
(1097,'http://www.rwbrownsbay.co.nz'),
(1099,'http://www.toast.-co.nz'),
(1100,'http://www.saywow.net.nz'),
(1101,'http://www.thehomeloanstore.co.nz'),
(1102,'http://www.driveline.co.nz'),
(1104,'http://www.bydizine.co.nz'),
(1106,'http://www.sanda.co.nz'),
(1107,'http://www.sendsationalgifts.co.nz'),
(1109,'http://www.heatpumpservlces.co.nz'),
(1112,'http://www.klassickitchens.co.nz');
